name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./

      - name: Install frontend dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_ROLLBAR_CLIENT_TOKEN: ${{ secrets.VITE_ROLLBAR_CLIENT_TOKEN }}